version: '3'

services:
  api1:
    build:
      context: .
      dockerfile: Dockerfile.api1
    ports:
      - "3001:3001"  # Optional, nur für Debugging

  api2:
    build:
      context: .
      dockerfile: Dockerfile.api2
    ports:
      - "3002:3002"  # Optional, nur für Debugging

  api3:
    build:
      context: .
      dockerfile: Dockerfile.api3
    ports:
      - "3003:3003"  # Optional, nur für Debugging

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - api1
      - api2
      - api3